// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function tlib(repo, files, save_to) {
  console.log("repo = " + repo + " | files = [" + files.join() + "] | save_to = " + save_to);
  
}

exports.tlib = tlib;
/* No side effect */
